# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11c7b985934b5c5aba7fe9cac421ba18b5d63f1c1b290792da8e5ab16c64e86ed70d6a78a3a51f30135ab1ec3da70a7095c1371c765c23bd301103b46fa51697

test:
  secret_key_base: eea38f36a700e21b2bed0f660b2672bc6d8265d7a0dabd3ad7997454f6cfb90bca145800fe30ecb31ce16fe22f4d4e11e4c427c697f26783dba6a4d4f9c4a2a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
